
server:
  port: 8854

spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: reader-yaml-config
          uri: http://localhost:8081/
          predicates:
            - Path=/reader-yaml-config/**
          filters:
            - StripPrefix=1
        - id: reader-discovery-config
          uri: lb://data-reader-service
          predicates:
            - Path=/reader-discovery-config/**
          filters:
            - StripPrefix=1

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8765/eureka

management:
  security.enabled: false
  endpoints.web.exposure.include: '*'

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG