
# Reading all employees from datasource-service
http://localhost:8082/employees

###

# Reading all employees with data-reader-service which calls datasource-service
# using feign client and eureka

http://localhost:8081/read/employees/feign


###

# Reading all employees with data-reader-service which calls datasource-service
# using http client

http://localhost:8081/read/employees/http-client
