
server:
  port: 8754

spring:
  application:
    name: zuul-gateway

management:
  security.enabled: false
  endpoints.web.exposure.include: '*'

logging:
  level:
    com.netflix: DEBUG


eureka:
  instance.preferIpAddress: true
  client:
    fetchRegistry: true
    service-url:
      defaultZone: "http://localhost:8765/eureka/"

zuul:
  debug:
    request: true
  # setting global prefix
  #prefix: /read/
  routes:
    reader:
      path: /reader/**
      url: http://localhost:8081/
      # Set stripPrefix to false if the prefix should not be stripped. This has effect on zuul.prefix not on the path
      # stripPrefix: false
    reader-discovery:
      path: /reader-discovery/**
      serviceId: data-reader-service
